on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n acr11052020 -g acr1105202098b2-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n acr11052020 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n acr11052020 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n acr11052020 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: acr11052020.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t acr11052020.azurecr.io/myakscluster:${{ github.sha }}
        docker push acr11052020.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myakscluster5596 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myakscluster5596`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myakscluster5596
        container-registry-url: acr11052020.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: myakscluster5596
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          acr11052020.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth